# Site settings
title: Alice PD Trainings
subsiteid: "alice-lessons"

email: storytelling@montana.edu
description: >
  Alice Lessons Professional Development
lang: en-US
remote_theme: aksakalli/jekyll-doc-theme@gh-pages
baseurl: "/alice-lessons-pd" # the subpath of your site, e.g. /blog/
url:  https://montanastorytelling.github.io/alice-lessons-pd # the base hostname & protocol for your site
git_address: https://github.com/montanastorytelling/alice-lessons-pd

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: cerulean # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  # Resources unavailable for sharing due to copyright
  - /f/backup/
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
  - .DS_Store

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
- scope:
    path: _permalinks
    type: permalinks
  values:
    layout: default
    seo:
      type: "WebPage"
- scope:
    path: _testing
    type: testing
  values:
    # permalink: /:collection/:name/
    layout: default
    seo:
      type: "WebPage"

# Disqus
disqus-shortname: thedevslot

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
